// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASmKNKkIWy_5F4U0PkcnGReBTjnKyOnDg',
    appId: '1:632210147021:web:34cc473ab5670640d98b84',
    messagingSenderId: '632210147021',
    projectId: 'chat-app-1e26a',
    authDomain: 'chat-app-1e26a.firebaseapp.com',
    storageBucket: 'chat-app-1e26a.firebasestorage.app',
    measurementId: 'G-GWX2FDYRQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByf4MkIzpCc8VSDj_j0HfkKzJxS4FuRHs',
    appId: '1:632210147021:android:80f838028d492790d98b84',
    messagingSenderId: '632210147021',
    projectId: 'chat-app-1e26a',
    storageBucket: 'chat-app-1e26a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOsLCmL_O8gO32XptViAG3rvLhqNAwdMM',
    appId: '1:632210147021:ios:dd451e7ad7de1cf8d98b84',
    messagingSenderId: '632210147021',
    projectId: 'chat-app-1e26a',
    storageBucket: 'chat-app-1e26a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOsLCmL_O8gO32XptViAG3rvLhqNAwdMM',
    appId: '1:632210147021:ios:dd451e7ad7de1cf8d98b84',
    messagingSenderId: '632210147021',
    projectId: 'chat-app-1e26a',
    storageBucket: 'chat-app-1e26a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASmKNKkIWy_5F4U0PkcnGReBTjnKyOnDg',
    appId: '1:632210147021:web:0eea99633efff26ad98b84',
    messagingSenderId: '632210147021',
    projectId: 'chat-app-1e26a',
    authDomain: 'chat-app-1e26a.firebaseapp.com',
    storageBucket: 'chat-app-1e26a.firebasestorage.app',
    measurementId: 'G-9V9ZQXDDRL',
  );
}
